### PR TITLE
restrict sdk version to 4.20.x to fix #56

### LINKED ISSUE #56: build broken with latest sdk (4.22.0)
```
compile 'com.facebook.android:audience-network-sdk:4.+'
```

The library dependency refers to all 4.* version
it's broken at 4.22.0 (fine with 4.20.0)

```
/Users/elvis/work/XXX/node_modules/react-native-fbads/src/android/src/main/java/io/callstack/react/fbads/BannerView.java:21: error: BannerView is not abst
ract and does not override abstract method onLoggingImpression(Ad) in AdListener
public class BannerView extends ReactViewGroup implements AdListener, LifecycleEventListener {
       ^
/Users/elvis/work/XXX/node_modules/react-native-fbads/src/android/src/main/java/io/callstack/react/fbads/InterstitialAdManager.java:13: error: Interstitia
lAdManager is not abstract and does not override abstract method onLoggingImpression(Ad) in AdListener
public class InterstitialAdManager extends ReactContextBaseJavaModule implements InterstitialAdListener, LifecycleEventListener {
       ^
Note: /Users/elvis/work/cybertool/node_modules/react-native-fbads/src/android/src/main/java/io/callstack/react/fbads/BannerViewManager.java uses unchecked or un
safe operations.
```

### PR DESCRIPTION
**Pull request by ElvisChiang**
quick fix build for sdk API change

### CODE REVIEW

**Comment by satya164** [comment]
Thank you

**Comment by alexandrebini** [comment]
Hi there!

When will it be released?

Tks

**Comment by satya164** [comment]
cc @grabbou

**Comment by grabbou** [comment]
Published as 4.1.1.

**Pull request merged**
