### PR TITLE
Remove `constantsToExports` usage

### LINKED ISSUE #65: error with didFailWithError
i am getting this error for most of the time, it works mostly though - 

screenshot at jul 04 02-46-37

any thoughts how we could fix this?

### LINKED ISSUE #67: [Request] Do not use `constantsToExport` on iOS
We currently export current device hash, so that it can be passed to `addTestDevice:`. We could change it in a way that `addTestDevice:` accepts a string of value "current" and we check for that value on a native side.

### PR DESCRIPTION
**Pull request by grabbou**
Fixes #67

### CODE REVIEW

**Comment by grabbou** [comment]
@satya164 I didn't author the Android part as far as reading constants. Please check if that's valid Java and let me know 🗡

**Comment by satya164** [comment]
Android looks good apart from the indentation

**Comment by grabbou** [comment]
Not sure how did it get through. Fixed.

**Comment by asgvard** [comment]
Commented on commit itself, but probably better to add it here:

Getting this error during Release build now:

react-native-fbads/src/android/src/main/java/io/callstack/react/fbads/AdSettingsManager.java:35: error: illegal start of expression
        if (deviceHashedId === "current") {
                             ^
Not sure what's wrong though. Happened after upgrading to fbads 4.2.1, which contains this change it seems.

**Comment by grabbou** [comment]
We have already fixed that - sorry, too much Javascript and triple equality
check got through

**Pull request merged**
